AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: operationDate
          AttributeType: S
        - AttributeName: operationTime
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: operationDateTime-index
          KeySchema:
            - AttributeName: operationDate
              KeyType: HASH
            - AttributeName: operationTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      TableName: certificationManagementInfo

      TimeToLiveSpecification:
        AttributeName: operationDateTime
        Enabled: true
