AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slipNo
          AttributeType: S
        - AttributeName: slipAdminUserId
          AttributeType: S
        - AttributeName: slipAdminOfficeId
          AttributeType: S
        - AttributeName: slipAdminMechanicId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: serviceType
          AttributeType: S

      KeySchema:
        - AttributeName: slipNo
          KeyType: HASH

      GlobalSecondaryIndexes:

        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: serviceType
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: slipAdminUserId-index
          KeySchema:
            - AttributeName: slipAdminUserId
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - slipNo
              - category
              - adminDiv
              - title
              - areaNo1
              - areaNo2
              - price
              - bidMethod
              - bidderId
              - bidEndDate
              - explanation
              - displayDiv
              - serviceType
              - targetVehicleName
              - workAreaInfo
              - preferredDate
              - preferredTime
              - imageUrlList
            ProjectionType: INCLUDE


        - IndexName: slipAdminOfficeId-index
          KeySchema:
            - AttributeName: slipAdminOfficeId
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - slipNo
              - category
              - adminDiv
              - title
              - areaNo1
              - areaNo2
              - price
              - bidMethod
              - bidderId
              - bidEndDate
              - explanation
              - displayDiv
              - serviceType
              - targetVehicleName
              - workAreaInfo
              - preferredDate
              - preferredTime
              - imageUrlList
            ProjectionType: INCLUDE

        - IndexName: slipAdminMechanicId-index
          KeySchema:
            - AttributeName: slipAdminMechanicId
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - slipNo
              - category
              - adminDiv
              - title
              - areaNo1
              - areaNo2
              - price
              - bidMethod
              - bidderId
              - bidEndDate
              - explanation
              - displayDiv
              - serviceType
              - targetVehicleName
              - workAreaInfo
              - preferredDate
              - preferredTime
              - imageUrlList
            ProjectionType: INCLUDE

      TableName: completionSlip