AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: historyId
          AttributeType: S
        - AttributeName: slipNo
          AttributeType: S
        - AttributeName: officeId
          AttributeType: S
      KeySchema:
        - AttributeName: historyId
          KeyType: HASH
      GlobalSecondaryIndexes:

        - IndexName: slipNo-index
          KeySchema:
            - AttributeName: slipNo
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: officeId-index
          KeySchema:
            - AttributeName: officeId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

      TableName: historyInfoOffice