AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slipNo
          AttributeType: S
        - AttributeName: historyId
          AttributeType: S
        - AttributeName: mechanicId
          AttributeType: S
      KeySchema:
        - AttributeName: slipNo
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: historyId-index
          KeySchema:
            - AttributeName: historyId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: mechanicId-index
          KeySchema:
            - AttributeName: mechanicId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TableName: historyInfoMecha