AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: inquiryId
          AttributeType: S
        - AttributeName: inquiryUserId
          AttributeType: S
        - AttributeName: inquiryAdless
          AttributeType: S
        - AttributeName: anserDiv
          AttributeType: S
      KeySchema:
        - AttributeName: inquiryId
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: inquiryUserId-index
          KeySchema:
            - AttributeName: inquiryUserId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: inquiryAdless-index
          KeySchema:
            - AttributeName: inquiryAdless
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: anserDiv-index
          KeySchema:
            - AttributeName: anserDiv
              KeyType: HASH
          Projection:
            ProjectionType: ALL

      TableName: inquiryInfo
