AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: mechanicId
          AttributeType: S
        - AttributeName: validDiv
          AttributeType: S
        - AttributeName: adminUserId
          AttributeType: S
        - AttributeName: officeId
          AttributeType: S
        - AttributeName: areaNo1
          AttributeType: S
        - AttributeName: areaNo2
          AttributeType: S
      KeySchema:
        - AttributeName: mechanicId
          KeyType: HASH
        - AttributeName: validDiv
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: adminUserId-index
          KeySchema:
            - AttributeName: adminUserId
              KeyType: HASH
            - AttributeName: validDiv
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: officeId-index
          KeySchema:
            - AttributeName: officeId
              KeyType: HASH
            - AttributeName: validDiv
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: areaNo1AndAreaNo2-index
          KeySchema:
            - AttributeName: areaNo1
              KeyType: HASH
            - AttributeName: areaNo2
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      TableName: mechanicInfo
