AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: officeId
          AttributeType: S
        - AttributeName: officeArea1
          AttributeType: S
        - AttributeName: officeArea
          AttributeType: S
      KeySchema:
        - AttributeName: officeId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: areaNo1AndAreaNo2-index
          KeySchema:
            - AttributeName: officeArea1
              KeyType: HASH
            - AttributeName: officeArea
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      TableName: officeInfo
