AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slipNo
          AttributeType: S
        - AttributeName: deleteDiv
          AttributeType: S
        - AttributeName: areaNo1
          AttributeType: S
        - AttributeName: areaNo2
          AttributeType: S
        - AttributeName: displayDiv
          AttributeType: S
        - AttributeName: slipAdminOfficeId
          AttributeType: S
        - AttributeName: slipAdminMechanicId
          AttributeType: S
        - AttributeName: processStatus
          AttributeType: S

      KeySchema:
        - AttributeName: slipNo
          KeyType: HASH
        - AttributeName: deleteDiv
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: AlbumTitleIndex
          KeySchema:
            - AttributeName: slipNo
              KeyType: HASH
            - AttributeName: displayDiv
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      GlobalSecondaryIndexes:

        - IndexName: areaNo1-index
          KeySchema:
            - AttributeName: areaNo1
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - slipNo
              - deleteDiv
              - category
              - slipAdminUserId
              - adminDiv
              - title
              - areaNo1
              - areaNo2
              - price
              - bidMethod
              - bidEndDate
              - processStatus
              - targetService
              - targetVehicleName
              - targetVehicleInfo
              - workAreaInfo
              - preferredDate
              - preferredTime
              - thumbnailUrl
            ProjectionType: INCLUDE

        - IndexName: areaNo1AndAreaNo2-index
          KeySchema:
            - AttributeName: areaNo1
              KeyType: HASH
            - AttributeName: areaNo2
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - slipNo
              - deleteDiv
              - category
              - slipAdminUserId
              - adminDiv
              - title
              - areaNo1
              - areaNo2
              - price
              - bidMethod
              - bidEndDate
              - processStatus
              - targetService
              - targetVehicleName
              - targetVehicleInfo
              - workAreaInfo
              - preferredDate
              - preferredTime
              - thumbnailUrl
            ProjectionType: INCLUDE

        - IndexName: slipAdminOfficeId-index
          KeySchema:
            - AttributeName: slipAdminOfficeId
              KeyType: HASH
            - AttributeName: deleteDiv
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - slipNo
              - deleteDiv
              - category
              - slipAdminUserId
              - adminDiv
              - title
              - areaNo1
              - areaNo2
              - price
              - bidMethod
              - bidEndDate
              - processStatus
              - targetService
              - targetVehicleName
              - targetVehicleInfo
              - workAreaInfo
              - preferredDate
              - preferredTime
              - thumbnailUrl
            ProjectionType: INCLUDE

        - IndexName: slipAdminMechanic-index
          KeySchema:
            - AttributeName: slipAdminMechanicId
              KeyType: HASH
            - AttributeName: deleteDiv
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - slipNo
              - deleteDiv
              - category
              - slipAdminUserId
              - adminDiv
              - title
              - areaNo1
              - areaNo2
              - price
              - bidMethod
              - bidEndDate
              - processStatus
              - targetService
              - targetVehicleName
              - targetVehicleInfo
              - workAreaInfo
              - preferredDate
              - preferredTime
              - thumbnailUrl
            ProjectionType: INCLUDE

        - IndexName: processStatus-index
          KeySchema:
            - AttributeName: processStatus
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - slipNo
              - deleteDiv
              - processStatus
            ProjectionType: INCLUDE

      TableName: salesServiceInfo