AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: slipNo
          AttributeType: S
        - AttributeName: requestStatus
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: requestStatus
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: slipNo-index
          KeySchema:
            - AttributeName: slipNo
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TableName: serviceTransactionRequest
