AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slipNo
          AttributeType: S
        - AttributeName: deleteDiv
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: areaNo1
          AttributeType: S
        - AttributeName: areaNo2
          AttributeType: S
      KeySchema:
        - AttributeName: slipNo
          KeyType: HASH
        - AttributeName: deleteDiv
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: category-index
          KeySchema:
            - AttributeName: category
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: areaNo1-index
          KeySchema:
            - AttributeName: areaNo1
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: areaNo1AndAreaNo2-index
          KeySchema:
            - AttributeName: areaNo1
              KeyType: HASH
            - AttributeName: areaNo2
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: categoryAndAreaNo1-index
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: areaNo1
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: areaNo1AndCategory-index
          KeySchema:
            - AttributeName: areaNo1
              KeyType: HASH
            - AttributeName: category
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      TableName: slipDetailInfo