AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slipNo
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: mechanicId
          AttributeType: S
        - AttributeName: officeId
          AttributeType: S
        - AttributeName: serviceType
          AttributeType: S
        - AttributeName: deleteDiv
          AttributeType: S
        - AttributeName: completionScheduledDate
          AttributeType: N
        - AttributeName: ttlDate
          AttributeType: N

      KeySchema:
        - AttributeName: slipNo
          KeyType: HASH

      GlobalSecondaryIndexes:

        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: serviceType
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: mechanicId-index
          KeySchema:
            - AttributeName: mechanicId
              KeyType: HASH
            - AttributeName: serviceType
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: officeId-index
          KeySchema:
            - AttributeName: officeId
              KeyType: HASH
            - AttributeName: serviceType
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: deleteDiv-index
          KeySchema:
            - AttributeName: deleteDiv
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: completionScheduledDate-index
          KeySchema:
            - AttributeName: deleteDiv
              KeyType: HASH
            - AttributeName: completionScheduledDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: ttlDate-index
          KeySchema:
            - AttributeName: deleteDiv
              KeyType: HASH
            - AttributeName: ttlDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      TableName: transactionSlip