AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: serviceType
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: mechanicId
          AttributeType: S
        - AttributeName: officeId
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: serviceType
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: mechanicId-index
          KeySchema:
            - AttributeName: mechanicId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: officeId-index
          KeySchema:
            - AttributeName: officeId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

      TableName: userMyList
