AWSTemplateFormatVersion: 2010-09-09
Description: Code for DynamoDB
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: useId
          AttributeType: S
        - AttributeName: userValidDiv
          AttributeType: S
      KeySchema:
        - AttributeName: useId
          KeyType: HASH
        - AttributeName: userValidDiv
          KeyType: RANGE
      TableName: userInfo