AWSTemplateFormatVersion: 2010-09-09
Description: IaC for Lambda
Parameters:
  # LambdaにアタッチするIAMロールのARN
  LambdaRoleArn:
    Type: String
    Description: Role of Lambda Function
  # S3Buket:Lambdaコードの格納先S3Buket
  S3Buket:
    Type: String
    Description: S3Buket
  # Lambdaコード格納先のディレクトリ名
  LambdaCodeDirectory:
    Type: String
    Description: LambdaCodeDirectory
  # テンプレート格納先のURL
  TemplateUrl:
    Type: String
    Description: TemplateURL


Resources:

  BrowsingHistoryLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/browsingHistoryLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/browsingHistoryLambda.zip'


  CompletionSlipLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/completionSlipLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/completionSlipLambda.zip'


  EvaluationInfoLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/evaluationInfoLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/evaluationInfoLambda.zip'

  FactoryMechaImpletionLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/factoryMechaImpletionLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/factoryMechaImpletionLambda.zip'

  FactoryMechanicFavoriteLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/factoryMechanicFavoriteLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/factoryMechanicFavoriteLambda.zip'


  HistoryInfoMechaLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/historyInfoMechaLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/historyInfoMechaLambda.zip'

  HistoryInfoOfficeLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/historyInfoOfficeLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/historyInfoOfficeLambda.zip'

  MechanicInfoLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/mechanicInfoLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/mechanicInfoLambda.zip'

  OfficeInfoLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/officeInfoLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/officeInfoLambda.zip'

  SlipDetailInfoLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/slipDetailInfoLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/slipDetailInfoLambda.zip'

  SlipMegPrmUserLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/slipMegPrmUserLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/slipMegPrmUserLambda.zip'

  SlipMessageInfoLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/slipMessageInfoLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/slipMessageInfoLambda.zip'

  SlipQuestionLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/slipQuestionLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/slipQuestionLambda.zip'

  SlipVehicleLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/slipVehicleLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/slipVehicleLambda.zip'

  TransactionSlipLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/transactionSlipLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/transactionSlipLambda.zip'

  UserFavoriteLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/userFavoriteLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/userFavoriteLambda.zip'

  UserInfoLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/userInfoLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/userInfoLambda.zip'


  UserMyListLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/userMyListLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/userMyListLambda.zip'

  UserVehicleInfoLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/userVehicleInfoLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/userVehicleInfoLambda.zip'

  SalesServiceInfoLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/salesServiceInfoLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/salesServiceInfoLambda.zip'

  ServiceTransactionRequestLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/serviceTransactionRequestLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/serviceTransactionRequestLambda.zip'

  HistoryUserInfoLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/historyUserInfoLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/historyUserInfoLambda.zip'


  FactoryMechaInicItemLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/basic/factoryMechaInicItemLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/basic/zip'
          - '/factoryMechaInicItemLambda.zip'


Outputs:

  # BrowsingHistoryLambdaのARN
  BrowsingHistoryLambda:
    Value: !GetAtt BrowsingHistoryLambda.Outputs.BrowsingHistoryLambda

  # CompletionSlipLambdaのARN
  CompletionSlipLambda:
    Value: !GetAtt CompletionSlipLambda.Outputs.CompletionSlipLambda

  # EvaluationInfoLambdaのARN
  EvaluationInfoLambda:
    Value: !GetAtt EvaluationInfoLambda.Outputs.EvaluationInfoLambda

  # FactoryMechaImpletionLambdaのARN
  FactoryMechaImpletionLambda:
    Value: !GetAtt FactoryMechaImpletionLambda.Outputs.FactoryMechaImpletionLambda

  # FactoryMechanicFavoriteLambdaのARN
  FactoryMechanicFavoriteLambda:
    Value: !GetAtt FactoryMechanicFavoriteLambda.Outputs.FactoryMechanicFavoriteLambda

  # HistoryInfoMechaLambdaのARN
  HistoryInfoMechaLambda:
    Value: !GetAtt HistoryInfoMechaLambda.Outputs.HistoryInfoMechaLambda

  # HistoryInfoOfficeLambdaのARN
  HistoryInfoOfficeLambda:
    Value: !GetAtt HistoryInfoOfficeLambda.Outputs.HistoryInfoOfficeLambda

  # MechanicInfoLambdaのARN
  MechanicInfoLambda:
    Value: !GetAtt MechanicInfoLambda.Outputs.MechanicInfoLambda

  # OfficeInfoLambdaのARN
  OfficeInfoLambda:
    Value: !GetAtt OfficeInfoLambda.Outputs.OfficeInfoLambda

  # SlipDetailInfoLambdaのARN
  SlipDetailInfoLambda:
    Value: !GetAtt SlipDetailInfoLambda.Outputs.SlipDetailInfoLambda

  # SlipMegPrmUserLambdaのARN
  SlipMegPrmUserLambda:
    Value: !GetAtt SlipMegPrmUserLambda.Outputs.SlipMegPrmUserLambda

  # SlipMessageInfoLambdaのARN
  SlipMessageInfoLambda:
    Value: !GetAtt SlipMessageInfoLambda.Outputs.SlipMessageInfoLambda

  # SlipQuestionLambdaのARN
  SlipQuestionLambda:
    Value: !GetAtt SlipQuestionLambda.Outputs.SlipQuestionLambda

  # SlipVehicleLambdaのARN
  SlipVehicleLambda:
    Value: !GetAtt SlipVehicleLambda.Outputs.SlipVehicleLambda

  # TransactionSlipLambdaのARN
  TransactionSlipLambda:
    Value: !GetAtt TransactionSlipLambda.Outputs.TransactionSlipLambda

  # UserFavoriteLambdaのARN
  UserFavoriteLambda:
    Value: !GetAtt UserFavoriteLambda.Outputs.UserFavoriteLambda

  # UserInfoLambdaのARN
  UserInfoLambda:
    Value: !GetAtt UserInfoLambda.Outputs.UserInfoLambda

  # UserMyListLambdaのARN
  UserMyListLambda:
    Value: !GetAtt UserMyListLambda.Outputs.UserMyListLambda

  # UserVehicleInfoLambdaのARN
  UserVehicleInfoLambda:
    Value: !GetAtt UserVehicleInfoLambda.Outputs.UserVehicleInfoLambda

  # SalesServiceInfoLambdaのARN
  SalesServiceInfoLambda:
    Value: !GetAtt SalesServiceInfoLambda.Outputs.SalesServiceInfoLambda

  # ServiceTransactionRequestLambdaのARN
  ServiceTransactionRequestLambda:
    Value: !GetAtt ServiceTransactionRequestLambda.Outputs.ServiceTransactionRequestLambda

  # HistoryUserInfoLambdaのARN
  HistoryUserInfoLambda:
    Value: !GetAtt HistoryUserInfoLambda.Outputs.HistoryUserInfoLambda

  # FactoryMechaInicItemLambdaのARN
  FactoryMechaInicItemLambda:
    Value: !GetAtt FactoryMechaInicItemLambda.Outputs.FactoryMechaInicItemLambda

