AWSTemplateFormatVersion: 2010-09-09
Description: IaC for Lambda
Parameters:
  # LambdaにアタッチするIAMロールのARN
  LambdaRoleArn:
    Type: String
    Description: Role of Lambda Function
  # S3Buket:Lambdaコードの格納先S3Buket
  S3Buket:
    Type: String
    Description: S3Buket
  # Lambdaコード格納先のディレクトリ名
  LambdaCodeDirectory:
    Type: String
    Description: LambdaCodeDirectory
  # テンプレート格納先のURL
  TemplateUrl:
    Type: String
    Description: TemplateURL


Resources:

  BrowsingHistoryGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/browsingHistory-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/browsingHistory-gsi.zip'

  CompletionSlipGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/completionSlip-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/completionSlip-gsi.zip'

  EvaluationInfoGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/evaluationInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/evaluationInfo-gsi.zip'

  HistoryInfoMechaGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/historyInfoMecha-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/historyInfoMecha-gsi.zip'

  HistoryInfoOfficeGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/historyInfoOffice-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/historyInfoOffice-gsi.zip'


  MechanicInfoGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/mechanicInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/mechanicInfo-gsi.zip'


  SlipDetailInfoGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/slipDetailInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/slipDetailInfo-gsi.zip'

  SlipQuestionGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/slipQuestion-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/slipQuestion-gsi.zip'

  TransactionSlipGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/transactionSlip-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/transactionSlip-gsi.zip'


  UserFavoriteGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/userFavorite-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/userFavorite-gsi.zip'

  UserMyListGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/userMyList-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/userMyList-gsi.zip'

  UserVehicleInfoGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/userVehicleInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/userVehicleInfo-gsi.zip'

  SalesServiceInfoGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/salesServiceInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/salesServiceInfo-gsi.zip'


Outputs:

  # BrowsingHistory-gsiのARN
  BrowsingHistoryGSILambda:
    Value: !GetAtt BrowsingHistoryGSI.Outputs.BrowsingHistoryGSILambda

  # CompletionSlip-gsiのARN
  CompletionSlipGSILambda:
    Value: !GetAtt CompletionSlipGSI.Outputs.CompletionSlipGSILambda

  # EvaluationInfo-gsiのARN
  EvaluationInfoGSILambda:
    Value: !GetAtt EvaluationInfoGSI.Outputs.EvaluationInfoGSILambda

  # HistoryInfoMecha-gsiのARN
  HistoryInfoMechaGSILambda:
    Value: !GetAtt HistoryInfoMechaGSI.Outputs.HistoryInfoMechaGSILambda

  # HistoryInfoOffice-gsiのARN
  HistoryInfoOfficeGSILambda:
    Value: !GetAtt HistoryInfoOfficeGSI.Outputs.HistoryInfoOfficeGSILambda

  # MechanicInfo-gsiのARN
  MechanicInfoGSILambda:
    Value: !GetAtt MechanicInfoGSI.Outputs.MechanicInfoGSILambda

  # SlipDetailInfo-gsiのARN
  SlipDetailInfoGSILambda:
    Value: !GetAtt SlipDetailInfoGSI.Outputs.SlipDetailInfoGSILambda

  # SlipQuestion-gsiのARN
  SlipQuestionGSILambda:
    Value: !GetAtt SlipQuestionGSI.Outputs.SlipQuestionGSILambda

  # TransactionSlip-gsiのARN
  TransactionSlipGSILambda:
    Value: !GetAtt TransactionSlipGSI.Outputs.TransactionSlipGSILambda

  # UserFavorite-gsiのARN
  UserFavoriteGSILambda:
    Value: !GetAtt UserFavoriteGSI.Outputs.UserFavoriteGSILambda

  # UserMyList-gsiのARN
  UserMyListGSILambda:
    Value: !GetAtt UserMyListGSI.Outputs.UserMyListGSILambda

  # UserVehicleInfo-gsiのARN
  UserVehicleInfoGSILambda:
    Value: !GetAtt UserVehicleInfoGSI.Outputs.UserVehicleInfoGSILambda

  # SalesServiceInfo-gsiのARN
  SalesServiceInfoGSILambda:
    Value: !GetAtt SalesServiceInfoGSI.Outputs.SalesServiceInfoGSILambda

