AWSTemplateFormatVersion: 2010-09-09
Description: IaC for Lambda
Parameters:
  # LambdaにアタッチするIAMロールのARN
  LambdaRoleArn:
    Type: String
    Description: Role of Lambda Function
  # S3Buket:Lambdaコードの格納先S3Buket
  S3Buket:
    Type: String
    Description: S3Buket
  # Lambdaコード格納先のディレクトリ名
  LambdaCodeDirectory:
    Type: String
    Description: LambdaCodeDirectory
  # テンプレート格納先のURL
  TemplateUrl:
    Type: String
    Description: TemplateURL


Resources:

  BrowsingHistoryGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/browsingHistory-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/browsingHistory-gsi.zip'

  CompletionSlipGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/completionSlip-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/completionSlip-gsi.zip'

  EvaluationInfoGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/evaluationInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/evaluationInfo-gsi.zip'

  HistoryInfoMechaGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/historyInfoMecha-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/historyInfoMecha-gsi.zip'

  HistoryInfoOfficeGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/historyInfoOffice-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/historyInfoOffice-gsi.zip'


  SlipDetailInfoGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/slipDetailInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/slipDetailInfo-gsi.zip'

  SlipQuestionGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/slipQuestion-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/slipQuestion-gsi.zip'

  TransactionSlipGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/transactionSlip-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/transactionSlip-gsi.zip'


  UserFavoriteGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/userFavorite-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/userFavorite-gsi.zip'

  UserMyListGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/userMyList-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/userMyList-gsi.zip'

  UserVehicleInfoGSI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/gsi/userVehicleInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/gsi/zip'
          - '/userVehicleInfo-gsi.zip'


Outputs:

  # BrowsingHistory-gsiのARN
  BrowsingHistoryGSI:
    Value: !GetAtt BrowsingHistoryGSI.Outputs.BrowsingHistoryGSILambda

  # CompletionSlip-gsiのARN
  CompletionSlipGSI:
    Value: !GetAtt CompletionSlipGSI.Outputs.CompletionSlipGSILambda

  # EvaluationInfo-gsiのARN
  EvaluationInfoGSI:
    Value: !GetAtt EvaluationInfoGSI.Outputs.EvaluationInfoGSILambda

  # HistoryInfoMecha-gsiのARN
  HistoryInfoMechaGSI:
    Value: !GetAtt HistoryInfoMechaGSI.Outputs.HistoryInfoMechaGSILambda

  # HistoryInfoOffice-gsiのARN
  HistoryInfoOfficeGSI:
    Value: !GetAtt HistoryInfoOfficeGSI.Outputs.HistoryInfoOfficeGSILambda

  # SlipDetailInfo-gsiのARN
  SlipDetailInfoGSI:
    Value: !GetAtt SlipDetailInfoGSI.Outputs.SlipDetailInfoGSILambda

  # SlipQuestion-gsiのARN
  SlipQuestionGSI:
    Value: !GetAtt SlipQuestionGSI.Outputs.SlipQuestionGSILambda

  # TransactionSlip--gsiのARN
  TransactionSlipGSI:
    Value: !GetAtt TransactionSlipGSI.Outputs.TransactionSlipGSILambda

  # UserFavorite-gsiのARN
  UserFavoriteGSI:
    Value: !GetAtt UserFavoriteGSI.Outputs.UserFavoriteGSILambda

  # UserMyList-gsiのARN
  UserMyListGSI:
    Value: !GetAtt UserMyListGSI.Outputs.UserMyListGSILambda

  # UserVehicleInfo-gsiのARN
  UserVehicleInfoGSI:
    Value: !GetAtt UserVehicleInfoGSI.Outputs.UserVehicleInfoGSILambda
