AWSTemplateFormatVersion: 2010-09-09
Description: IaC for Lambda
Parameters:
  # LambdaにアタッチするIAMロールのARN
  LambdaRoleArn:
    Type: String
    Description: Role of Lambda Function
  # S3Buket:Lambdaコードの格納先S3Buket
  S3Buket:
    Type: String
    Description: S3Buket
  # S3Key:Lambdaコードの格納先
  S3Key:
    Type: String
    Description: S3Key


Resources:

  BrowsingHistory-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/browsingHistory-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/browsingHistory-gsi.zip'

  CompletionSlip-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/completionSlip-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/completionSlip-gsi.zip'

  EvaluationInfo-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/evaluationInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/evaluationInfo-gsi.zip'

  HistoryInfoMecha-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/historyInfoMecha-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/historyInfoMecha-gsi.zip'

  HistoryInfoOffice-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/historyInfoOffice-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/historyInfoOffice-gsi.zip'


  SlipDetailInfo-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/slipDetailInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/slipDetailInfo-gsi.zip'

  SlipQuestion-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/slipQuestion-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/slipQuestion-gsi.zip'

  TransactionSlip-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/transactionSlip-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/transactionSlip-gsi.zip'


  UserFavorite-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/userFavorite-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/userFavorite-gsi.zip'

  UserMyList-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/userMyList-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/userMyList-gsi.zip'

  UserVehicleInfo-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/userVehicleInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/userVehicleInfo-gsi.zip'


Outputs:



  # BrowsingHistory-gsiのARN
  BrowsingHistory-gsi:
    Value: !GetAtt BrowsingHistory-gsi.Outputs.BrowsingHistoryGSILambda

  # CompletionSlip-gsiのARN
  CompletionSlip-gsi:
    Value: !GetAtt CompletionSlip-gsi.Outputs.CompletionSlipGSILambda

  # EvaluationInfo-gsiのARN
  EvaluationInfo-gsi:
    Value: !GetAtt EvaluationInfo-gsi.Outputs.EvaluationInfoGSILambda

  # HistoryInfoMecha-gsiのARN
  HistoryInfoMecha-gsi:
    Value: !GetAtt HistoryInfoMecha-gsi.Outputs.HistoryInfoMechaGSILambda

  # HistoryInfoOffice-gsiのARN
  HistoryInfoOffice-gsi:
    Value: !GetAtt HistoryInfoOffice-gsi.Outputs.HistoryInfoOfficeGSILambda

  # SlipDetailInfo-gsiのARN
  SlipDetailInfo-gsi:
    Value: !GetAtt SlipDetailInfo-gsi.Outputs.SlipDetailInfoGSILambda

  # SlipMessageInfo-gsi のARN
  SlipMessageInfo-gsi :
    Value: !GetAtt SlipMessageInfo-gsi .Outputs.SlipMessageInfoGSILambda

  # SlipQuestion-gsiのARN
  SlipQuestion-gsi:
    Value: !GetAtt SlipQuestion-gsi.Outputs.SlipQuestionGSILambda

  # TransactionSlip--gsiのARN
  TransactionSlip-gsi:
    Value: !GetAtt TransactionSlip-gsi.Outputs.TransactionSlipGSILambda

  # UserFavorite-gsiのARN
  UserFavorite-gsi:
    Value: !GetAtt UserFavorite-gsi.Outputs.UserFavoriteGSILambda

  # UserMyList-gsiのARN
  UserMyList-gsi:
    Value: !GetAtt UserMyList-gsi.Outputs.UserMyListGSILambda

  # UserVehicleInfo-gsiのARN
  UserVehicleInfo-gsi:
    Value: !GetAtt UserVehicleInfo-gsi.Outputs.UserVehicleInfoGSILambda
