AWSTemplateFormatVersion: "2010-09-09"
Description: Manage myself verification environment

Parameters:
  # LambdaCode格納先のS3Buketを記述
  S3Buket:
    Type: String
    Description: S3Buket
  # テンプレート格納先のURL
  TemplateUrl:
    Type: String
    Description: TemplateURL
  # Lambdaコード格納先のディレクトリ名
  LambdaCodeDirectory:
    Type: String
    Description: LambdaCodeDirectory


Resources:

  # Roleの作成
  Role:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'iam/hakomecha-role.yaml'


  # DynamoDBの作成
  DynamoDBRoot:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'tbl-root.yaml'
      Parameters:
        TemplateUrl: !Join 
        - ''
        - - !Ref TemplateUrl

  # Lambdaの作成
  BasicLambdaRoot:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'basic-lambda-root.yaml'
      Parameters:
        LambdaRoleArn: !GetAtt Role.Outputs.DynamoDBAccessRole
        S3Buket: !Ref S3Buket
        LambdaCodeDirectory: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
        TemplateUrl: !Join 
        - ''
        - - !Ref TemplateUrl


  GsiLambdaRoot:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'gsi-lambda-root.yaml'
      Parameters:
        LambdaRoleArn: !GetAtt Role.Outputs.DynamoDBAccessRole
        S3Buket: !Ref S3Buket
        LambdaCodeDirectory: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
        TemplateUrl: !Join 
        - ''
        - - !Ref TemplateUrl

  CheckLambdaRoot:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'check-lambda-root.yaml'
      Parameters:
        LambdaRoleArn: !GetAtt Role.Outputs.DynamoDBAccessRole
        S3Buket: !Ref S3Buket
        LambdaCodeDirectory: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
        TemplateUrl: !Join 
        - ''
        - - !Ref TemplateUrl

  UniqueLambdaRoot:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'unique-lambda-root.yaml'
      Parameters:
        LambdaRoleArn: !GetAtt Role.Outputs.DynamoDBAccessRole
        S3Buket: !Ref S3Buket
        LambdaCodeDirectory: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
        TemplateUrl: !Join 
        - ''
        - - !Ref TemplateUrl

  SlipProcessLambdaRoot:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'slipProcess-lambda-root.yaml'
      Parameters:
        LambdaRoleArn: !GetAtt Role.Outputs.DynamoDBAccessRole
        S3Buket: !Ref S3Buket
        LambdaCodeDirectory: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
        TemplateUrl: !Join 
        - ''
        - - !Ref TemplateUrl


  InternalLambdaRoot:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'internal-lambda-root.yaml'
      Parameters:
        LambdaRoleArn: !GetAtt Role.Outputs.DynamoDBAccessRole
        S3Buket: !Ref S3Buket
        LambdaCodeDirectory: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
        TemplateUrl: !Join 
        - ''
        - - !Ref TemplateUrl


  AuthLambdaRoot:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'auth-lambda-root.yaml'
      Parameters:
        LambdaRoleArn: !GetAtt Role.Outputs.DynamoDBAccessRole
        S3Buket: !Ref S3Buket
        LambdaCodeDirectory: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
        TemplateUrl: !Join 
        - ''
        - - !Ref TemplateUrl

  # Cognitoの作成
  Cognito:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'cognito/hakomecha-cognito.yaml'


  # APIGatewayの作成
  BasicApigateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'basic-apigateway.yaml'
      Parameters:
        BrowsingHistoryLambdaArn: !GetAtt BasicLambdaRoot.Outputs.BrowsingHistoryLambda
        CompletionSlipLambdaArn: !GetAtt BasicLambdaRoot.Outputs.CompletionSlipLambda
        EvaluationInfoLambdaArn: !GetAtt BasicLambdaRoot.Outputs.EvaluationInfoLambda
        HistoryInfoMechaLambdaArn: !GetAtt BasicLambdaRoot.Outputs.HistoryInfoMechaLambda
        HistoryInfoOfficeLambdaArn: !GetAtt BasicLambdaRoot.Outputs.HistoryInfoOfficeLambda
        MechanicInfoLambdaArn: !GetAtt BasicLambdaRoot.Outputs.MechanicInfoLambda
        OfficeInfoLambdaArn: !GetAtt BasicLambdaRoot.Outputs.OfficeInfoLambda
        SlipDetailInfoLambdaArn: !GetAtt BasicLambdaRoot.Outputs.SlipDetailInfoLambda
        SlipMegPrmUserLambdaArn: !GetAtt BasicLambdaRoot.Outputs.SlipMegPrmUserLambda
        SlipMessageInfoLambdaArn: !GetAtt BasicLambdaRoot.Outputs.SlipMessageInfoLambda
        SlipQuestionLambdaArn: !GetAtt BasicLambdaRoot.Outputs.SlipQuestionLambda
        SlipVehicleLambdaArn: !GetAtt BasicLambdaRoot.Outputs.SlipVehicleLambda
        TransactionSlipLambdaArn: !GetAtt BasicLambdaRoot.Outputs.TransactionSlipLambda
        UserFavoriteLambdaArn: !GetAtt BasicLambdaRoot.Outputs.UserFavoriteLambda
        UserInfoLambdaArn: !GetAtt BasicLambdaRoot.Outputs.UserInfoLambda
        UserMyListLambdaArn: !GetAtt BasicLambdaRoot.Outputs.UserMyListLambda
        UserVehicleInfoLambdaArn: !GetAtt BasicLambdaRoot.Outputs.UserVehicleInfoLambda
        SalesServiceInfoLambdaArn: !GetAtt BasicLambdaRoot.Outputs.SalesServiceInfoLambda
        FactoryMechaImpletionLambdaArn: !GetAtt BasicLambdaRoot.Outputs.FactoryMechaImpletionLambda
        FactoryMechanicFavoriteLambdaArn: !GetAtt BasicLambdaRoot.Outputs.FactoryMechanicFavoriteLambda
        ServiceTransactionRequestLambdaArn: !GetAtt BasicLambdaRoot.Outputs.ServiceTransactionRequestLambda
        HistoryUserInfoLambdaArn: !GetAtt BasicLambdaRoot.Outputs.HistoryUserInfoLambda
        FactoryMechaInicItemLambdaArn: !GetAtt BasicLambdaRoot.Outputs.FactoryMechaInicItemLambda
        InquiryInfoLambdaArn: !GetAtt BasicLambdaRoot.Outputs.InquiryInfoLambda

        UserPoolArn: !GetAtt Cognito.Outputs.UserPoolArn

  GsiApigateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'gsi-apigateway.yaml'
      Parameters:
        BrowsingHistoryGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.BrowsingHistoryGSILambda
        CompletionSlipGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.CompletionSlipGSILambda
        EvaluationInfoGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.EvaluationInfoGSILambda
        HistoryInfoMechaGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.HistoryInfoMechaGSILambda
        HistoryInfoOfficeGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.HistoryInfoOfficeGSILambda
        SlipDetailInfoGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.SlipDetailInfoGSILambda
        SlipQuestionGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.SlipQuestionGSILambda
        SlipMessageInfoGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.SlipMessageInfoGSILambda
        TransactionSlipGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.TransactionSlipGSILambda
        UserFavoriteGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.UserFavoriteGSILambda
        UserMyListGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.UserMyListGSILambda
        MechanicInfoGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.MechanicInfoGSILambda
        UserVehicleInfoGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.UserVehicleInfoGSILambda
        SalesServiceInfoGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.SalesServiceInfoGSILambda
        FactoryMechaImpletionGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.FactoryMechaImpletionGSILambda
        FactoryMechanicFavoriteGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.FactoryMechanicFavoriteGSILambda
        ServiceTransactionRequestGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.ServiceTransactionRequestGSILambda
        HistoryUserInfoGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.HistoryUserInfoGSILambda
        SerchServiceContentsGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.SerchServiceContentsGSILambda
        SerchSlipContentsGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.SerchSlipContentsGSILambda
        FactoryMechaInicItemsGSILambdaArn: !GetAtt GsiLambdaRoot.Outputs.FactoryMechaInicItemsGSILambda

        UserPoolArn: !GetAtt Cognito.Outputs.UserPoolArn


  CheckApigateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'check-apigateway.yaml'
      Parameters:
        SlipMegPrmUserCheckLambdaArn: !GetAtt CheckLambdaRoot.Outputs.SlipMegPrmUserCheckLambda
        SlipAdminUserCheckLambdaArn: !GetAtt CheckLambdaRoot.Outputs.SlipAdminUserCheckLambda
        CheckAcceseAdminLambdaArn: !GetAtt CheckLambdaRoot.Outputs.CheckAcceseAdminLambda
        ServiceTransactionReqUserCheckLambdaArn: !GetAtt CheckLambdaRoot.Outputs.ServiceTransactionReqUserCheckLambda
        ServiceTransactionUserCheckLambdaArn: !GetAtt CheckLambdaRoot.Outputs.ServiceTransactionUserCheckLambda

        UserPoolArn: !GetAtt Cognito.Outputs.UserPoolArn


  UniqueApigateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'unique-apigateway.yaml'
      Parameters:
        GetSlipLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.GetSlipLambda
        GetSalesServiceLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.GetSalesServiceLambda
        MessageParmRequestLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.MessageParmRequestLambda
        MultipleBrowsingHistoryLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.MultipleBrowsingHistoryLambda
        MultipleFavoriteLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.MultipleFavoriteLambda
        InitPostSlipLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.InitPostSlipLambda
        InitMechanicUserLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.InitMechanicUserLambda
        InitOfficeLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.InitOfficeLambda
        InitSalesServiceLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.InitSalesServiceLambda
        SerchSalesServiceContentsLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.SerchSalesServiceContentsLambda
        SerchslipContentsLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.SerchslipContentsLambda
        SendSlipMessageLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.SendSlipMessageLambda
        SendSlipQuestionLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.SendSlipQuestionLambda
        SalesAdminInfoLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.SalesAdminInfoLambda
        SlipAdminInfoLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.SlipAdminInfoLambda
        PastTransactionLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.PastTransactionLambda
        SerchRequestMechanicInfoLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.SerchRequestMechanicInfoLambda
        EditConnectionOfficeStatusLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.EditConnectionOfficeStatusLambda
        SerchFcMcInfoLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.SerchFcMcInfoLambda
        FcmcItemSerchLambdaArn: !GetAtt UniqueLambdaRoot.Outputs.FcmcItemSerchLambda
        UserPoolArn: !GetAtt Cognito.Outputs.UserPoolArn


  SlipProcessApigateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'slipProcess-apigateway.yaml'
      Parameters:
        ConfirmTransactionLambdaArn: !GetAtt SlipProcessLambdaRoot.Outputs.ConfirmTransactionLambda
        SendTransactionRequestLambdaArn: !GetAtt SlipProcessLambdaRoot.Outputs.SendTransactionRequestLambda
        TransactionEndLambdaArn: !GetAtt SlipProcessLambdaRoot.Outputs.TransactionEndLambda
        RelistedServiceLambdaArn: !GetAtt SlipProcessLambdaRoot.Outputs.RelistedServiceLambda

        UserPoolArn: !GetAtt Cognito.Outputs.UserPoolArn


  AuthApigateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'auth-apigateway.yaml'
      Parameters:
        LogOutLambdaArn: !GetAtt AuthLambdaRoot.Outputs.LogOutLambda

        UserPoolArn: !GetAtt Cognito.Outputs.UserPoolArn



  # S3（画像アップロード用）の作成
  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 's3/hakomecha-s3-upload.yaml'
      Parameters:
        S3BucketName: 'hakomecha-s3-upload'


Outputs:
  # 構築したリージョン
  Region:
    Value: !Ref AWS::Region
    Description: Region
  # CognitoIDプールID
  CognitoIdentityPoolId:
    Value: !GetAtt Cognito.Outputs.IdentityPool
    Description: Cognito IdentityPoolId
  # CognitoユーザープールID
  CognitoUserPoolId:
    Value: !GetAtt Cognito.Outputs.UserPoolId
    Description: Cognito UserPoolId
  # CognitoアプリケーションクライアントID
  CognitoClientId:
    Value: !GetAtt Cognito.Outputs.UserPoolClient
    Description: Cognito ClientId
  # 画像アップロード用S3バケット名
  S3UploadBucketName:
    Value: !GetAtt S3.Outputs.S3BucketName
    Description: S3 Upload BucketName
