AWSTemplateFormatVersion: 2010-09-09
Description: IaC for Lambda
Parameters:
  # LambdaにアタッチするIAMロールのARN
  LambdaRoleArn:
    Type: String
    Description: Role of Lambda Function
  # S3Buket:Lambdaコードの格納先S3Buket
  S3Buket:
    Type: String
    Description: S3Buket
  # Lambdaコード格納先のディレクトリ名
  LambdaCodeDirectory:
    Type: String
    Description: LambdaCodeDirectory
  # テンプレート格納先のURL
  TemplateUrl:
    Type: String
    Description: TemplateURL


Resources:

  InternalAdminCheckLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/internal/internalAdminCheckLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/internal/zip'
          - '/internalAdminCheckLambda.zip'


  InternalFcMcItemLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/internal/internalFcMcItemLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/internal/zip'
          - '/internalFcMcItemLambda.zip'


  InternalMoveSlipProcessStatusLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/internal/internalMoveSlipProcessStatusLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/internal/zip'
          - '/internalMoveSlipProcessStatusLambda.zip'


  InternalRequestMsgApproveAndOtherLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/internal/internalRequestMsgApproveAndOtherLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/internal/zip'
          - '/internalRequestMsgApproveAndOtherLambda.zip'


  InternalSendMsgMylistLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/internal/internalSendMsgMylistLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/internal/zip'
          - '/internalSendMsgMylistLambda.zip'


Outputs:
  # InternalAdminCheckLambdaのARN
  InternalAdminCheckLambda:
    Value: !GetAtt InternalAdminCheckLambda.Outputs.InternalAdminCheckLambda

  # InternalFcMcItemLambdaのARN
  InternalFcMcItemLambda:
    Value: !GetAtt InternalFcMcItemLambda.Outputs.InternalFcMcItemLambda

  # InternalMoveSlipProcessStatusLambdaのARN
  InternalMoveSlipProcessStatusLambda:
    Value: !GetAtt InternalMoveSlipProcessStatusLambda.Outputs.InternalMoveSlipProcessStatusLambda

  # InternalRequestMsgApproveAndOtherLambdaのARN
  InternalRequestMsgApproveAndOtherLambda:
    Value: !GetAtt InternalRequestMsgApproveAndOtherLambda.Outputs.InternalRequestMsgApproveAndOtherLambda

  # InternalSendMsgMylistLambdaのARN
  InternalSendMsgMylistLambda:
    Value: !GetAtt InternalSendMsgMylistLambda.Outputs.InternalSendMsgMylistLambda

