AWSTemplateFormatVersion: 2010-09-09
Description: IaC for Lambda
Parameters:
  # LambdaにアタッチするIAMロールのARN
  LambdaRoleArn:
    Type: String
    Description: Role of Lambda Function
  # S3Buket:Lambdaコードの格納先S3Buket
  S3Buket:
    Type: String
    Description: S3Buket
  # Lambdaコード格納先のディレクトリ名
  LambdaCodeDirectory:
    Type: String
    Description: LambdaCodeDirectory
  # テンプレート格納先のURL
  TemplateUrl:
    Type: String
    Description: TemplateURL


Resources:

  ConfirmMigrationServiceLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/schedule_batch/confirmMigrationServiceLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/schedule_batch/zip'
          - '/confirmMigrationServiceLambda.zip'


  DeadlineCheckTransacitonServiceLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/schedule_batch/deadlineCheckTransacitonServiceLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/schedule_batch/zip'
          - '/deadlineCheckTransacitonServiceLambda.zip'


  ExpiredServiceLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/schedule_batch/expiredServiceLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/schedule_batch/zip'
          - '/expiredServiceLambda.zip'

  TransactionEndBatchLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/schedule_batch/transactionEndBatchLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/schedule_batch/zip'
          - '/transactionEndBatchLambda.zip'


Outputs:

  # ConfirmMigrationServiceLambdaのARN
  ConfirmMigrationServiceLambda:
    Value: !GetAtt ConfirmMigrationServiceLambda.Outputs.ConfirmMigrationServiceLambda

  # DeadlineCheckTransacitonServiceLambdaのARN
  DeadlineCheckTransacitonServiceLambda:
    Value: !GetAtt DeadlineCheckTransacitonServiceLambda.Outputs.DeadlineCheckTransacitonServiceLambda

  # ExpiredServiceLambdaのARN
  ExpiredServiceLambda:
    Value: !GetAtt ExpiredServiceLambda.Outputs.ExpiredServiceLambda

  # TransactionEndBatchLambdaのARN
  TransactionEndBatchLambda:
    Value: !GetAtt TransactionEndBatchLambda.Outputs.TransactionEndBatchLambda


