AWSTemplateFormatVersion: '2010-09-09'
Description: ' Lambda Sample'
Parameters:

  # SchedulerRoleArn‚ÌARN
  SchedulerRoleArn:
    Type: String

  # confirmMigrationServiceLambda‚ÌARN
  ConfirmMigrationServiceLambdaArn:
    Type: String

  # deadlineCheckTransacitonServiceLambda‚ÌARN
  DeadlineCheckTransacitonServiceLambdaArn:
    Type: String

  # expiredServiceLambda‚ÌARN
  ExpiredServiceLambdaArn:
    Type: String

  # transactionEndBatchLambda‚ÌARN
  TransactionEndBatchLambdaArn:
    Type: String

  # certificationScheduleLambda‚ÌARN
  CertificationScheduleLambdaArn:
    Type: String

  # expiredServiceDeleteLambda‚ÌARN
  ExpiredServiceDeleteLambdaArn:
    Type: String

  # expiredSlipDeleteLambda‚ÌARN
  ExpiredSlipDeleteLambdaArn:
    Type: String

Resources:


  # EventBridgeSchedule
  ConfirmMigrationServiceSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: ConfirmMigrationServiceSchedule
      ScheduleExpression: rate(12 hours)
      FlexibleTimeWindow:
        Mode: FLEXIBLE
        MaximumWindowInMinutes: 60
      State: ENABLED
      Target:
        Arn: !Ref ConfirmMigrationServiceLambdaArn
        RoleArn: !Ref SchedulerRoleArn


  DeadlineCheckTransacitonServiceSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: DeadlineCheckTransacitonService Schedule
      ScheduleExpression: rate(12 hours)
      FlexibleTimeWindow:
        Mode: FLEXIBLE
        MaximumWindowInMinutes: 60
      State: ENABLED
      Target:
        Arn: !Ref DeadlineCheckTransacitonServiceLambdaArn
        RoleArn: !Ref SchedulerRoleArn


  ExpiredServiceSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: ExpiredService Schedule
      ScheduleExpression: rate(12 hours)
      FlexibleTimeWindow:
        Mode: FLEXIBLE
        MaximumWindowInMinutes: 60
      State: ENABLED
      Target:
        Arn: !Ref ExpiredServiceLambdaArn
        RoleArn: !Ref SchedulerRoleArn

  TransactionEndBatchSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: TransactionEnd Batch Schedule
      ScheduleExpression: rate(12 hours)
      FlexibleTimeWindow:
        Mode: FLEXIBLE
        MaximumWindowInMinutes: 60
      State: ENABLED
      Target:
        Arn: !Ref TransactionEndBatchLambdaArn
        RoleArn: !Ref SchedulerRoleArn

  CertificationSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Certification End Schedule
      ScheduleExpression: rate(2 hours)
      FlexibleTimeWindow:
        Mode: FLEXIBLE
        MaximumWindowInMinutes: 60
      State: ENABLED
      Target:
        Arn: !Ref CertificationScheduleLambdaArn
        RoleArn: !Ref SchedulerRoleArn

  ExpiredServiceDeleteHourSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: TransactionEnd Batch Schedule
      ScheduleExpression: rate(12 hours)
      FlexibleTimeWindow:
        Mode: FLEXIBLE
        MaximumWindowInMinutes: 60
      State: ENABLED
      Target:
        Arn: !Ref ExpiredServiceDeleteLambdaArn
        RoleArn: !Ref SchedulerRoleArn

  ExpiredSlipDeleteHourSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Certification End Schedule
      ScheduleExpression: rate(2 hours)
      FlexibleTimeWindow:
        Mode: FLEXIBLE
        MaximumWindowInMinutes: 60
      State: ENABLED
      Target:
        Arn: !Ref ExpiredSlipDeleteLambdaArn
        RoleArn: !Ref SchedulerRoleArn


  # LambdaPermission
  PermissionForEventsToInvokeLambda1:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: confirmMigrationServiceLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 'ConfirmMigrationServiceSchedule.Arn'

  PermissionForEventsToInvokeLambda2:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: deadlineCheckTransacitonServiceLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 'DeadlineCheckTransacitonServiceSchedule.Arn'

  PermissionForEventsToInvokeLambda3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: expiredServiceLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 'ExpiredServiceSchedule.Arn'

  PermissionForEventsToInvokeLambda4:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: transactionEndBatchLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 'TransactionEndBatchSchedule.Arn'

  PermissionForEventsToInvokeLambda5:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: certificationScheduleLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 'CertificationSchedule.Arn'

  PermissionForEventsToInvokeLambda6:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: expiredServiceDeleteLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 'ExpiredServiceDeleteHourSchedule.Arn'

  PermissionForEventsToInvokeLambda7:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: expiredSlipDeleteLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 'ExpiredSlipDeleteHourSchedule.Arn'

