AWSTemplateFormatVersion: 2010-09-09
Description: IaC for Lambda
Parameters:
  # LambdaにアタッチするIAMロールのARN
  LambdaRoleArn:
    Type: String
    Description: Role of Lambda Function
  # S3Buket:Lambdaコードの格納先S3Buket
  S3Buket:
    Type: String
    Description: S3Buket
  # Lambdaコード格納先のディレクトリ名
  LambdaCodeDirectory:
    Type: String
    Description: LambdaCodeDirectory
  # テンプレート格納先のURL
  TemplateUrl:
    Type: String
    Description: TemplateURL


Resources:

  GetSlipLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/unique/getSlipLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/unique/zip'
          - '/getSlipLambda.zip'

  MessageParmRequestLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/unique/messageParmRequestLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/unique/zip'
          - '/messageParmRequestLambda.zip'

  InitPostSlipLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/unique/initPostSlipLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/unique/zip'
          - '/initPostSlipLambda.zip'

  InitMechanicUserLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/unique/initMechanicUserLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/unique/zip'
          - '/initMechanicUserLambda.zip'

  InitOfficeLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/unique/initOfficeLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/unique/zip'
          - '/initOfficeLambda.zip'

  InitSalesServiceLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/unique/initSalesServiceLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/unique/zip'
          - '/initSalesServiceLambda.zip'

  SerchSalesServiceContentsLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/unique/serchSalesServiceContentsLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/unique/zip'
          - '/serchSalesServiceContentsLambda.zip'

  SerchslipContentsLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/unique/serchslipContentsLambda.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/unique/zip'
          - '/serchslipContentsLambda.zip'

Outputs:

  # GetSlipLambdaのARN
  GetSlipLambda:
    Value: !GetAtt GetSlipLambda.Outputs.GetSlipLambda

  # MessageParmRequestLambdaのARN
  MessageParmRequestLambda:
    Value: !GetAtt MessageParmRequestLambda.Outputs.MessageParmRequestLambda

  # InitPostSlipLambdaのARN
  InitPostSlipLambda:
    Value: !GetAtt InitPostSlipLambda.Outputs.InitPostSlipLambda

  # InitMechanicUserLambdaのARN
  InitMechanicUserLambda:
    Value: !GetAtt InitMechanicUserLambda.Outputs.InitMechanicUserLambda

  # InitOfficeLambdaのARN
  InitOfficeLambda:
    Value: !GetAtt InitOfficeLambda.Outputs.InitOfficeLambda

  # InitSalesServiceLambdaのARN
  InitSalesServiceLambda:
    Value: !GetAtt InitSalesServiceLambda.Outputs.InitSalesServiceLambda

  # SerchSalesServiceContentsLambdaのARN
  SerchSalesServiceContentsLambda:
    Value: !GetAtt SerchSalesServiceContentsLambda.Outputs.SerchSalesServiceContentsLambda

  # SerchslipContentsLambdaのARN
  SerchslipContentsLambda:
    Value: !GetAtt SerchslipContentsLambda.Outputs.SerchslipContentsLambda
