AWSTemplateFormatVersion: 2010-09-09
Description: IaC for Lambda
Parameters:
  # LambdaにアタッチするIAMロールのARN
  LambdaRoleArn:
    Type: String
    Description: Role of Lambda Function
  # S3Buket:Lambdaコードの格納先S3Buket
  S3Buket:
    Type: String
    Description: S3Buket
  # S3Key:Lambdaコードの格納先
  S3Key:
    Type: String
    Description: S3Key


Resources:

  BrowsingHistory-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/browsingHistory-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/browsingHistory-gsi.zip'

  EvaluationInfo-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/evaluationInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/evaluationInfo-gsi.zip'

  HistoryInfoMecha-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/historyInfoMecha-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/historyInfoMecha-gsi.zip'

  HistoryInfoOffice-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/historyInfoOffice-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/historyInfoOffice-gsi.zip'


  SlipDetailInfo-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/slipDetailInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/slipDetailInfo-gsi.zip'

  SlipQuestion-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/slipQuestion-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/slipQuestion-gsi.zip'

  UserFavorite-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/userFavorite-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/userFavorite-gsi.zip'

  UserMyList-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/userMyList-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/userMyList-gsi.zip'

  UserVehicleInfo-gsi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join 
        - ''
        - - !Ref TemplateUrl
          - 'lambda/userVehicleInfo-gsi.yaml'
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        S3Buket: !Ref S3Buket
        S3Key: !Join 
        - ''
        - - !Ref LambdaCodeDirectory
          - '/userVehicleInfo-gsi.zip'


Outputs:



  # BrowsingHistory-gsiのARN
  BrowsingHistory-gsi:
    Value: !GetAtt BrowsingHistory-gsi.Outputs.BrowsingHistory-gsi

  # EvaluationInfo-gsiのARN
  EvaluationInfo-gsi:
    Value: !GetAtt EvaluationInfo-gsi.Outputs.EvaluationInfo-gsi

  # HistoryInfoMecha-gsiのARN
  HistoryInfoMecha-gsi:
    Value: !GetAtt HistoryInfoMecha-gsi.Outputs.HistoryInfoMecha-gsi

  # HistoryInfoOffice-gsiのARN
  HistoryInfoOffice-gsi:
    Value: !GetAtt HistoryInfoOffice-gsi.Outputs.HistoryInfoOffice-gsi

  # SlipDetailInfo-gsiのARN
  SlipDetailInfo-gsi:
    Value: !GetAtt SlipDetailInfo-gsi.Outputs.SlipDetailInfo-gsi

  # SlipMessageInfo-gsi のARN
  SlipMessageInfo-gsi :
    Value: !GetAtt SlipMessageInfo-gsi .Outputs.SlipMessageInfo-gsi 

  # SlipQuestion-gsiのARN
  SlipQuestion-gsi:
    Value: !GetAtt SlipQuestion-gsi.Outputs.SlipQuestion-gsi

  # UserFavorite-gsiのARN
  UserFavorite-gsi:
    Value: !GetAtt UserFavorite-gsi.Outputs.UserFavorite-gsi

  # UserMyList-gsiのARN
  UserMyList-gsi:
    Value: !GetAtt UserMyList-gsi.Outputs.UserMyList-gsi

  # UserVehicleInfo-gsiのARN
  UserVehicleInfo-gsi:
    Value: !GetAtt UserVehicleInfo-gsi.Outputs.UserVehicleInfo-gsi
