AWSTemplateFormatVersion: 2010-09-09
Description: ScheduledBatchRole
Resources:
  # IAMポリシー
  ScheduledBatchLambdaAccess:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Scheduled Batch Lambda Role.
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:*'
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
              - 'lambda:InvokeFunction'
            Resource:
              - '*'
  # IAMロール
  ScheduledBatchLambdaAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: UnauthenticatedRole for Cognito ID Pool.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service:
                - lambda.amazonaws.com
                - scheduler.amazonaws.com
      ManagedPolicyArns:
        - !Ref ScheduledBatchLambdaAccess
Outputs:
  # IAMロールのARN
  ScheduledBatchLambdaAccessRole:
    Value: !GetAtt ScheduledBatchLambdaAccessRole.Arn
